config/routes.rb
Rails.application.routes.draw do
  resources :cart_items
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :carts, except: [:show]
  resources :items
  resources :orders, only: [:create]
  resources :store_locations, only: [:index]
  resources :newsletter_subscribers, only: [:create]

  resources :users, only: [:update, :show]
  get 'profile', to: 'users#profile'
  get 'mycart', to: 'carts#show'

  # Route Stripe Checkout
  post 'create-checkout-session/:id', to: 'orders#create_payment', as: 'create-checkout-session'
  as :admin do
   authenticated :admin do
     root 'rails_admin/main#dashboard', as: :authenticated_root
   end

   unauthenticated do
     root 'devise/sessions#new', as: :unauthenticated_root
   end
 end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :item
  validates :quantity, numericality: {greater_than: 0, only_integer: true}

  def total_price
    return self.quantity*self.item.price
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :set_cart_item, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ create ]

  # GET /cart_items or /cart_items.json
  def index
    @cart_items = CartItem.all
  end

  # GET /cart_items/1 or /cart_items/1.json
  def show
  end

  # GET /cart_items/new
  def new
    @cart_item = CartItem.new
  end

  # GET /cart_items/1/edit
  def edit
  end

  # POST /cart_items or /cart_items.json
  def create
    @existing_item = CartItem.find_by(item_id: cart_item_params[:item_id], cart: current_user.cart)
    new_params = cart_item_params.to_h.merge(cart: current_user.cart)
    if @existing_item
        current_quantity = @existing_item.quantity
        @existing_item.update!(quantity: current_quantity + cart_item_params[:quantity].to_i)
        render json: @existing_item
    else
        @cart_item = CartItem.new(new_params)

        respond_to do |format|
          if @cart_item.save
            format.html { redirect_to @cart_item, notice: "Cart item was successfully created." }
            format.json { render :show, status: :created, location: @cart_item }
          else
            format.html { render :new, status: :unprocessable_entity }
            format.json { render json: @cart_item.errors, status: :unprocessable_entity }
          end
        end
    end
  end

  # PATCH/PUT /cart_items/1 or /cart_items/1.json
  def update
    respond_to do |format|
      if @cart_item.update(cart_item_params)
        format.html { redirect_to @cart_item, notice: "Cart item was successfully updated." }
        format.json { render :show, status: :ok, location: @cart_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cart_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cart_items/1 or /cart_items/1.json
  def destroy
    if @cart_item.cart.user == current_user
      @cart_item.destroy
      respond_to do |format|
        format.html { redirect_to cart_items_url, notice: "Cart item was successfully destroyed." }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to cart_items_url, status: :unprocessable_entity }
        format.json { render :json => {:error => "not-found"}.to_json, :status => 404 }
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart_item
      @cart_item = CartItem.find(params[:id])
    end
    
    # Only allow a list of trusted parameters through.
    def cart_item_params
      params.require(:cart_item).permit(:item_id, :quantity, :id)
    end
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/_form.html.erb
<%= form_with(model: cart_item) do |form| %>
  <% if cart_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart_item.errors.count, "error") %> prohibited this cart_item from being saved:</h2>

      <ul>
        <% cart_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cart_items/edit.html.erb
<h1>Editing Cart Item</h1>

<%= render 'form', cart_item: @cart_item %>

<%= link_to 'Show', @cart_item %> |
<%= link_to 'Back', cart_items_path %>

app/views/cart_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cart Items</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cart_items.each do |cart_item| %>
      <tr>
        <td><%= link_to 'Show', cart_item %></td>
        <td><%= link_to 'Edit', edit_cart_item_path(cart_item) %></td>
        <td><%= link_to 'Destroy', cart_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart Item', new_cart_item_path %>

app/views/cart_items/new.html.erb
<h1>New Cart Item</h1>

<%= render 'form', cart_item: @cart_item %>

<%= link_to 'Back', cart_items_path %>

app/views/cart_items/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cart_item_path(@cart_item) %> |
<%= link_to 'Back', cart_items_path %>